// project/src/app/core/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

interface NavItem {
  path: string;
  icon: string;
  label: string;
}

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
  navItems: NavItem[] = [
    { path: '/', icon: 'LayoutDashboard', label: 'Dashboard' },
    { path: '/orders', icon: 'Package', label: 'Orders' },
    { path: '/documents', icon: 'FileText', label: 'Documents' },
    { path: '/shipments', icon: 'Truck', label: 'Shipments' },
    { path: '/chat', icon: 'MessageSquare', label: 'Chat' }
  ];

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  logout(): void {
    this.authService.logout();
    this.router.navigate(['/auth/login']);
  }
}
<nav class="bg-gradient-to-r from-white to-primary-50 shadow-lg border-b-4 border-primary-500">
  <div class="container mx-auto px-4">
    <div class="flex justify-between items-center h-16">
      <a routerLink="/" class="flex items-center space-x-2 group">
        <div class="bg-gradient-to-r from-primary-500 to-primary-600 p-2 rounded-lg shadow-lg">
          <i class="text-white text-2xl" lucide-icon="Package"></i>
        </div>
        <span class="text-xl font-bold bg-gradient-to-r from-primary-600 to-primary-800 bg-clip-text text-transparent">
          ExportEdge
        </span>
      </a>

      <div class="hidden md:flex items-center space-x-8">
        <ng-container *ngFor="let item of navItems">
          <a [routerLink]="item.path"
             routerLinkActive="active"
             [routerLinkActiveOptions]="{exact: item.path === '/'}"
             class="nav-link">
            <i [lucide-icon]="item.icon" class="h-5 w-5"></i>
            <span>{{item.label}}</span>
          </a>
        </ng-container>
      </div>

      <div class="flex items-center space-x-4">
        <button (click)="logout()" 
                class="flex items-center space-x-2 text-gray-600 hover:text-primary-600 transition-colors duration-200">
          <i lucide-icon="LogOut" class="h-5 w-5"></i>
          <span>Logout</span>
        </button>
      </div>
    </div>
  </div>
</nav>

// project/src/components/Navbar.tsx
import React from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../contexts/AuthContext';
import { 
  ShoppingBagIcon,
  DocumentTextIcon,
  TruckIcon,
  ChatBubbleLeftRightIcon,
  HomeIcon,
  ArrowRightOnRectangleIcon
} from '@heroicons/react/24/outline';
import LanguageSelector from './LanguageSelector';

const Navbar = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { t } = useTranslation();
  const { logout } = useAuth();

  const handleLogout = () => {
    logout();
    navigate('/');
  };

  const navItems = [
    { path: '/dashboard', icon: HomeIcon, label: t('dashboard') },
    { path: '/orders', icon: ShoppingBagIcon, label: t('orders') },
    { path: '/documents', icon: DocumentTextIcon, label: t('documents') },
    { path: '/shipments', icon: TruckIcon, label: t('shipments') },
    { path: '/chat', icon: ChatBubbleLeftRightIcon, label: t('chat') },
  ];

  const isActive = (path: string) => {
    return location.pathname === path ? 'active' : '';
  };

  return (
    <nav className="bg-white shadow-lg border-b border-gray-200">
      <div className="container mx-auto px-4">
        <div className="flex justify-between items-center h-16">
          <Link to="/" className="flex items-center space-x-2 group">
            <motion.div
              whileHover={{ rotate: 360 }}
              transition={{ duration: 0.5 }}
              className="bg-gradient-to-r from-primary-500 to-accent-500 p-2 rounded-xl shadow-lg"
            >
              <ShoppingBagIcon className="h-8 w-8 text-white" />
            </motion.div>
            <span className="text-xl font-bold bg-gradient-to-r from-primary-600 to-accent-600 bg-clip-text text-transparent">
              ExportEdge
            </span>
          </Link>

          <div className="hidden md:flex items-center space-x-8">
            {navItems.map((item) => (
              <motion.div
                key={item.path}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                <Link
                  to={item.path}
                  className={`nav-link ${isActive(item.path)}`}
                >
                  <item.icon className="h-5 w-5" />
                  <span>{item.label}</span>
                </Link>
              </motion.div>
            ))}
          </div>

          <div className="flex items-center space-x-4">
            <LanguageSelector />
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={handleLogout}
              className="flex items-center space-x-2 text-gray-600 hover:text-primary-600 transition-colors duration-200"
            >
              <ArrowRightOnRectangleIcon className="h-5 w-5" />
              <span>{t('logout')}</span>
            </motion.button>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
