// project/src/app/shared/components/date-range-filter/date-range-filter.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

export interface DateRange {
  start: Date | null;
  end: Date | null;
}

@Component({
  selector: 'app-date-range-filter',
  templateUrl: './date-range-filter.component.html'
})
export class DateRangeFilterComponent {
  @Input() selectedRange: string = '';
  @Input() customRange: DateRange = { start: null, end: null };
  @Output() rangeChange = new EventEmitter<string>();
  @Output() customRangeChange = new EventEmitter<DateRange>();

  ranges = [
    { value: '', label: 'All Time' },
    { value: 'today', label: 'Today' },
    { value: 'yesterday', label: 'Yesterday' },
    { value: 'week', label: 'Last 7 Days' },
    { value: 'month', label: 'Last 30 Days' },
    { value: 'custom', label: 'Custom Range' }
  ];

  onRangeChange(value: string): void {
    this.rangeChange.emit(value);
  }

  onCustomRangeChange(type: 'start' | 'end', date: Date): void {
    const newRange = {
      ...this.customRange,
      [type]: date
    };
    this.customRangeChange.emit(newRange);
  }
}
<div class="flex items-center space-x-4">
  <select
    [ngModel]="selectedRange"
    (ngModelChange)="onRangeChange($event)"
    class="rounded-lg border-gray-300 text-sm focus:ring-primary-500 focus:border-primary-500"
  >
    <option *ngFor="let range of ranges" [value]="range.value">
      {{ range.label }}
    </option>
  </select>

  <ng-container *ngIf="selectedRange === 'custom'">
    <div class="flex items-center space-x-2">
      <div class="relative">
        <i lucide-icon="Calendar" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4"></i>
        <input
          type="date"
          [ngModel]="customRange.start"
          (ngModelChange)="onCustomRangeChange('start', $event)"
          class="pl-10 rounded-lg border-gray-300 text-sm focus:ring-primary-500 focus:border-primary-500"
          placeholder="Start Date"
        />
      </div>
      <span class="text-gray-500">to</span>
      <div class="relative">
        <i lucide-icon="Calendar" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4"></i>
        <input
          type="date"
          [ngModel]="customRange.end"
          (ngModelChange)="onCustomRangeChange('end', $event)"
          class="pl-10 rounded-lg border-gray-300 text-sm focus:ring-primary-500 focus:border-primary-500"
          placeholder="End Date"
        />
      </div>
    </div>
  </ng-container>
</div>

// project/src/components/common/DateRangeFilter.tsx
import React from 'react';
import { CalendarIcon } from '@heroicons/react/24/outline';
import DatePicker from 'react-datepicker';
import "react-datepicker/dist/react-datepicker.css";

interface DateRangeFilterProps {
  dateRange: 'today' | 'yesterday' | 'week' | 'month' | 'custom' | null;
  customDateRange: {
    start: string | null;
    end: string | null;
  };
  onDateRangeChange: (range: 'today' | 'yesterday' | 'week' | 'month' | 'custom' | null) => void;
  onCustomDateChange: (dates: { start: string | null; end: string | null }) => void;
}

const DateRangeFilter: React.FC<DateRangeFilterProps> = ({
  dateRange,
  customDateRange,
  onDateRangeChange,
  onCustomDateChange,
}) => {
  return (
    <div className="flex items-center space-x-4">
      <select
        value={dateRange || ''}
        onChange={(e) => onDateRangeChange(e.target.value as any)}
        className="rounded-lg border-gray-300 text-sm focus:ring-primary-500 focus:border-primary-500"
      >
        <option value="">All Time</option>
        <option value="today">Today</option>
        <option value="yesterday">Yesterday</option>
        <option value="week">Last 7 Days</option>
        <option value="month">Last 30 Days</option>
        <option value="custom">Custom Range</option>
      </select>

      {dateRange === 'custom' && (
        <div className="flex items-center space-x-2">
          <div className="relative">
            <CalendarIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
            <DatePicker
              selected={customDateRange.start ? new Date(customDateRange.start) : null}
              onChange={(date) => onCustomDateChange({
                ...customDateRange,
                start: date ? date.toISOString() : null
              })}
              className="pl-10 rounded-lg border-gray-300 text-sm focus:ring-primary-500 focus:border-primary-500"
              placeholderText="Start Date"
            />
          </div>
          <span className="text-gray-500">to</span>
          <div className="relative">
            <CalendarIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
            <DatePicker
              selected={customDateRange.end ? new Date(customDateRange.end) : null}
              onChange={(date) => onCustomDateChange({
                ...customDateRange,
                end: date ? date.toISOString() : null
              })}
              className="pl-10 rounded-lg border-gray-300 text-sm focus:ring-primary-500 focus:border-primary-500"
              placeholderText="End Date"
            />
          </div>
        </div>
      )}
    </div>
  );
};

export default DateRangeFilter;
